# Generated by Django 6.1.1 on 2026-10-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaurants',
            new_name='Restaurant',
        ),
    ]
